### ISSUE TITLE
conda-lock error in main when specifying version with >=

### ISSUE THREAD

**Issue by lesteve** [conda-incubator/conda-lock#144]
It works fine with 0.13.2.

### To reproduce

test-environment.yml
```yml
channels:
  - conda-forge

dependencies:
  - numpy >= 1.12
```

```
mamba create -n test-env conda-lock -y
conda activate test-env
pip install git+https://github.com/conda-incubator/conda-lock
conda-lock -p linux-64 -f test-environment.yml
conda-lock -p linux-64 -f test-environment.yml
```

the conda command is using `numpy[version='>=1.12']` whereas it should probably use `numpy[version>=1.12]`.

<details>

<summary>Full output</summary>
 
```
Locking dependencies for ['linux-64']...
    Command: ['/home/lesteve/miniconda3/bin/conda', 'create', '--prefix', '/tmp/tmp54316my3/prefix', '--dry-run', '--json', '--override-channels', '--channel', 'conda-forge', '--channel', 'file:///tmp/tmpve4rgqn2', "numpy[version='>= 1.12']"]
    STDOUT:
{
  "caused_by": "None",
  "error": "CondaValueError: invalid package specification: numpy[version='>= 1.12']",
  "exception_name": "CondaValueError",
  "exception_type": "<class 'conda.exceptions.CondaValueError'>",
  "message": "invalid package specification: numpy[version='>= 1.12']"
}


Could not lock the environment for platform linux-64
invalid package specification: numpy[version='>= 1.12']
    Command: ['/home/lesteve/miniconda3/bin/conda', 'create', '--prefix', '/tmp/tmp54316my3/prefix', '--dry-run', '--json', '--override-channels', '--channel', 'conda-forge', '--channel', 'file:///tmp/tmpve4rgqn2', "numpy[version='>= 1.12']"]
    STDOUT:
{
  "caused_by": "None",
  "error": "CondaValueError: invalid package specification: numpy[version='>= 1.12']",
  "exception_name": "CondaValueError",
  "exception_type": "<class 'conda.exceptions.CondaValueError'>",
  "message": "invalid package specification: numpy[version='>= 1.12']"
}


Traceback (most recent call last):
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lesteve/dev/conda-lock/conda_lock/__main__.py", line 4, in <module>
    main()
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/lesteve/dev/conda-lock/conda_lock/conda_lock.py", line 1074, in lock
    lock_func(
  File "/home/lesteve/dev/conda-lock/conda_lock/conda_lock.py", line 873, in run_lock
    make_lock_files(
  File "/home/lesteve/dev/conda-lock/conda_lock/conda_lock.py", line 311, in make_lock_files
    lock_content = lock_content | create_lockfile_from_spec(
  File "/home/lesteve/dev/conda-lock/conda_lock/conda_lock.py", line 643, in create_lockfile_from_spec
    deps = _solve_for_arch(
  File "/home/lesteve/dev/conda-lock/conda_lock/conda_lock.py", line 595, in _solve_for_arch
    conda_deps = solve_conda(
  File "/home/lesteve/dev/conda-lock/conda_lock/conda_solver.py", line 134, in solve_conda
    dry_run_install = solve_specs_for_arch(
  File "/home/lesteve/dev/conda-lock/conda_lock/conda_solver.py", line 298, in solve_specs_for_arch
    proc.check_returncode()
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/subprocess.py", line 456, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/home/lesteve/miniconda3/bin/conda', 'create', '--prefix', '/tmp/tmp54316my3/prefix', '--dry-run', '--json', '--override-channels', '--channel', 'conda-forge', '--channel', 'file:///tmp/tmpve4rgqn2', "numpy[version='>= 1.12']"]' returned non-zero exit status 1.
```

</details>

**Comment by mariusvniekerk** [comment]
technically the spaces after the operators are not allowed in much of the conda ecosystem.  Easy enough though to just strip the whitespace away from those parts
