### ISSUE TITLE
Error in main when using blas[build=mkl] in environment.yml

### ISSUE THREAD

**Issue by lesteve** [conda-incubator/conda-lock#148]
Trying to use conda-lock with an environment.yml that has `blas[build=mkl]`
creates a `KeyError` on main. This seems to work fine with 0.13.2.

To reproduce:

```bash
cat << EOF > test-environment.yml
channels:
  - conda-forge

dependencies:
  - numpy
  - blas[build=mkl]
EOF
 
mamba create -n test-env conda-lock -y                       
conda activate test-env
pip install git+https://github.com/conda-incubator/conda-lock
conda-lock -p linux-64 -f test-environment.yml
```

```
❯ conda-lock lock -p linux-64 -f test-environment.yml 
<re.Match object; span=(0, 19), match='  - blas[build=mkl]'>
('  - blas', None, 'build=mkl')
Traceback (most recent call last):
  File "/home/lesteve/miniconda3/envs/conda-lock/bin/conda-lock", line 8, in <module>
    sys.exit(main())
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 1074, in lock
    lock_func(
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 873, in run_lock
    make_lock_files(
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 270, in make_lock_files
    lock_spec = make_lock_spec(
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 199, in make_lock_spec
    lock_specs = parse_source_files(
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 713, in parse_source_files
    desired_envs.append(parse_environment_file(src_file, pip_support))
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/conda_lock/src_parser/environment_yaml.py", line 48, in parse_environment_file
    filtered_content = "\n".join(filter_platform_selectors(content, platform=None))
  File "/home/lesteve/miniconda3/envs/conda-lock/lib/python3.10/site-packages/conda_lock/src_parser/selectors.py", line 28, in filter_platform_selectors
    if cond in platform_sel[platform]:
KeyError: None
```

**Comment by mariusvniekerk** [comment]
Looks like it is treating this as a selector?

**Comment by lesteve** [comment]
Indeed, I do get the same error.

By the way, I tried the alternative `blas=*=mkl` syntax and I get another type of error in main, I opened #151 about this.

**Comment by ogrisel** [comment]
For reference, here is the recommended way to select a particular BLAS variant when installing packages from conda-forge:

https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation

**Comment by ogrisel** [comment]
For reference, when using the syntax `libblas=*=*mkl` in the `environment.yml` file, one gets:

```
Locking dependencies for ['linux-64']...
Could not lock the environment for platform linux-64
invalid package specification: libblas[version='=*=*mkl']
    Command: ['/Users/ogrisel/mambaforge/bin/conda', 'create', '--prefix', '/var/folders/_y/lfnx34p13w3_sr2k12bjb05w0000gn/T/tmp8tug_n2j/prefix', '--dry-run', '--json', '--override-channels', '--channel', 'conda-forge', '--channel', 'file:///var/folders/_y/lfnx34p13w3_sr2k12bjb05w0000gn/T/tmp_ctlcue_', 'numpy', "libblas[version='=*=*mkl']", 'scipy', 'cython', 'joblib', 'threadpoolctl', 'pandas', 'matplotlib', 'pyamg', 'pillow', "pytest[version='=6.2.5']", 'pytest-xdist', 'codecov', 'pytest-cov', "coverage[version='=6.2']", 'ccache']
    STDOUT:
{
  "caused_by": "None",
  "error": "CondaValueError: invalid package specification: libblas[version='=*=*mkl']",
  "exception_name": "CondaValueError",
  "exception_type": "<class 'conda.exceptions.CondaValueError'>",
  "message": "invalid package specification: libblas[version='=*=*mkl']"
}
```
