### ISSUE TITLE
PermissionError when trying to conda-lock install on Windows

### ISSUE THREAD

**Issue by lesteve** [conda-incubator/conda-lock#165]
To reproduce (I tried with the latest development version https://github.com/conda-incubator/conda-lock/commit/4ec8031540f778e81d0e18c864d4716069d6e0a7 at the time of writing):

```bash 
# test-environment.yml
channels:
  - conda-forge

dependencies:
  - pyyaml
```

```bash
conda-lock lock -p win-64 -f test-environment.yml
conda-lock install conda-lock.yml
```

Output:
```
Traceback (most recent call last):
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\Scripts\conda-lock.exe\__main__.py", line 7, in <module>
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\site-packages\conda_lock\conda_lock.py", line 1232, in install
    install_func(file=lockfile)
  File "C:\Users\lesteve\mambaforge\envs\conda-lock\lib\site-packages\conda_lock\conda_lock.py", line 189, in do_conda_install
    with open(file) as explicit_env:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\lesteve\\AppData\\Local\\Temp\\tmp9bwcxyih'
```

Wild-guess this may be related to a `NamedTemporaryFile` quirk on Windows, kind of what this code is working around https://github.com/conda-incubator/conda-lock/blob/4ec8031540f778e81d0e18c864d4716069d6e0a7/conda_lock/conda_lock.py#L771-L778 but in another place in the code?

Note I am seeing that in a [CI log](https://dev.azure.com/scikit-learn/scikit-learn/_build/results?buildId=39142&view=logs&j=0238e32a-2fbb-5be1-f782-cfff4ef2924e&t=b9700462-e87c-5d04-086a-80b788924915&l=351) as well, so I kind of doubt this is something specific to my Windows VM setup.

**Comment by mariusvniekerk** [comment]
Yeah looks like that same silly workaround is needed here https://github.com/conda-incubator/conda-lock/blob/4ec8031540f778e81d0e18c864d4716069d6e0a7/conda_lock/conda_lock.py#L857-L867
