### ISSUE TITLE
Error in case conda-lock is started from another drive than the default temporary directory lies on

### ISSUE THREAD

**Issue by wagnerpeer** [conda-incubator/conda-lock#175]
Hi there

I am using `conda-lock` for a while now and I am experiencing issues since the update to the new major version.

Issue
-----
If I run `conda-lock` from a path where the drive is different to the drive from the path of the lockfile I want to generate, the process crashes with a `ValueError: Paths don't have the same drive`.

Environment
--------------
Current `conda-lock`  version installed: `1.0.2=pyhd8ed1ab_0`
System used: `Windows 10 Enterprise 20H2`

Details
-------
I am using a full build-recipe for `conda-build`, a `meta.yaml` file as source.

The invocation is equivalent to:
```conda lock -p win-64 --file E:\recipe\meta.yaml --lockfile C:\Temp\lock.lock```

The issue lies in conda_lock\common.py, line 122, in the function `relative_path`. There is an implicit assumption, that the source and target paths have a common drive.

All `1.x.x` versions show this behavior, whereas the last prior version `0.13.2` is working as expected.

**Comment by wagnerpeer** [comment]
Sure.

Full output from the mentioned command:

```shell
C:\Users\Username\Miniconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1654, in parseString
    raise exc
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 6), (line:1, col:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Username\Miniconda3\Scripts\conda-lock-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 1166, in lock
    lock_func(
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 936, in run_lock
    make_lock_files(
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 335, in make_lock_files
    lock_spec = make_lock_spec(
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 241, in make_lock_spec
    lock_specs = parse_source_files(
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 764, in parse_source_files
    parse_meta_yaml_file(src_file, list(platform_overrides))
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\src_parser\meta_yaml.py", line 98, in parse_meta_yaml_file
    [
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\src_parser\meta_yaml.py", line 99, in <listcomp>
    _parse_meta_yaml_file_for_platform(meta_yaml_file, platform)
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\src_parser\meta_yaml.py", line 156, in _parse_meta_yaml_file_for_platform
    add_requirements_from_recipe_or_output(meta_yaml_data)
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\src_parser\meta_yaml.py", line 152, in add_requirements_from_recipe_or_output
    add_spec(s, "main")
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\src_parser\meta_yaml.py", line 138, in add_spec
    dep = parse_python_requirement(
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\src_parser\pyproject_toml.py", line 239, in parse_python_requirement
    parsed_req = Requirement.parse(requirement_specifier)
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\__init__.py", line 3134, in parse
    req, = parse_requirements(s)
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\__init__.py", line 3089, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "C:\Users\Username\Miniconda3\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 104, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'=3'": Expected stringEnd

```

**Comment by wagnerpeer** [comment]
Sorry. Mixed this with the other issue I filed yesterday. 🙈 

```shell
C:\Users\Username\Miniconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Locking dependencies for ['win-64']...
INFO:conda_lock.conda_solver:win-64 using specs ['python >=3.0']
Traceback (most recent call last):
  File "C:\Users\Username\Miniconda3\Scripts\conda-lock-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Username\Miniconda3\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 1166, in lock
    lock_func(
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 936, in run_lock
    make_lock_files(
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 388, in make_lock_files
    lock_content = lock_content | create_lockfile_from_spec(
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 739, in create_lockfile_from_spec
    sources=[
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 740, in <listcomp>
    relative_path(lockfile_path.parent, source) for source in spec.sources
  File "C:\Users\Username\Miniconda3\lib\site-packages\conda_lock\common.py", line 122, in relative_path
    os.path.commonpath((source.resolve(strict=True), target.resolve(strict=True)))
  File "C:\Users\Username\Miniconda3\lib\ntpath.py", line 763, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive
```
