### ISSUE TITLE
solver error: conda-forge::albumentations with pytorch::pytorch

### ISSUE THREAD

**Issue by croth1** [conda-incubator/conda-lock#221]
Hey there! Can you help me understand why this won't solve for me?

```
# testenv.yaml
name: testenv

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - pytorch=1.12
  - albumentations=1.2.1
```

<details>
  <summary>conda-lock  --mamba -f testenv.yaml -p osx-64</summary>
  
```
Locking dependencies for ['osx-64']...
INFO:conda_lock.conda_solver:osx-64 using specs ['python 3.9.*', 'pytorch 1.12.*', 'albumentations 1.2.1.*']
Failed to parse json, Expecting value: line 1 column 1 (char 0)
Could not lock the environment for platform osx-64
Encountered problems while solving:
  - nothing provides libopencv 4.5.0 py36_5 needed by opencv-4.5.0-py36_5


    Command: ['/Users/christian/miniconda3/bin/mamba', 'create', '--prefix', '/var/folders/55/85jcdk9d7wqbvjdk0cxh34qw0000gn/T/tmp2z3vsl7x/prefix', '--dry-run', '--json', '--override-channels', '--channel', 'pytorch', '--channel', 'conda-forge', '--channel', 'file:///var/folders/55/85jcdk9d7wqbvjdk0cxh34qw0000gn/T/tmptt8_jgru', 'python 3.9.*', 'pytorch 1.12.*', 'albumentations 1.2.1.*']
    STDOUT:
Encountered problems while solving:
  - nothing provides libopencv 4.5.0 py36_5 needed by opencv-4.5.0-py36_5


Traceback (most recent call last):
  File "/Users/christian/miniconda3/bin/conda-lock", line 10, in <module>
    sys.exit(main())
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 1170, in lock
    lock_func(
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 940, in run_lock
    make_lock_files(
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 388, in make_lock_files
    lock_content = lock_content | create_lockfile_from_spec(
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 726, in create_lockfile_from_spec
    deps = _solve_for_arch(
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 678, in _solve_for_arch
    conda_deps = solve_conda(
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_lock/conda_solver.py", line 159, in solve_conda
    dry_run_install = solve_specs_for_arch(
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_lock/conda_solver.py", line 346, in solve_specs_for_arch
    proc.check_returncode()
  File "/Users/christian/miniconda3/lib/python3.9/site-packages/poetry/utils/_compat.py", line 168, in check_returncode
    raise CalledProcessError(
poetry.utils._compat.CalledProcessError: Command '['/Users/christian/miniconda3/bin/mamba', 'create', '--prefix', '/var/folders/55/85jcdk9d7wqbvjdk0cxh34qw0000gn/T/tmp2z3vsl7x/prefix', '--dry-run', '--json', '--override-channels', '--channel', 'pytorch', '--channel', 'conda-forge', '--channel', 'file:///var/folders/55/85jcdk9d7wqbvjdk0cxh34qw0000gn/T/tmptt8_jgru', 'python 3.9.*', 'pytorch 1.12.*', 'albumentations 1.2.1.*']' returned non-zero exit status 1.
```
</details>

<details>
  <summary>mamba env create -f testenv.yaml --dry-run</summary>
 
```
conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache
Transaction

  Prefix: /var/folders/55/85jcdk9d7wqbvjdk0cxh34qw0000gn/T/tmpsrbhvzuy

  Updating specs:

   - python=3.9
   - pytorch=1.12
   - albumentations=1.2.1


  Package                           Version  Build               Channel                  Size
────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────

  + albumentations                    1.2.1  pyhd8ed1ab_0        conda-forge/noarch       88kB
  + aom                               3.3.0  h96cf925_1          conda-forge/osx-64        3MB
  + blas                              2.115  mkl                 conda-forge/osx-64       13kB
  + blas-devel                        3.9.0  15_osx64_mkl        conda-forge/osx-64       12kB
  + blosc                            1.21.1  h97e831e_3          conda-forge/osx-64       49kB
  + brotli                            1.0.9  h5eb16cf_7          conda-forge/osx-64       18kB
  + brotli-bin                        1.0.9  h5eb16cf_7          conda-forge/osx-64       18kB
  + brunsli                             0.1  h046ec9c_0          conda-forge/osx-64      183kB
  + bzip2                             1.0.8  h0d85af4_4          conda-forge/osx-64     Cached
  + c-ares                           1.18.1  h0d85af4_0          conda-forge/osx-64     Cached
  + c-blosc2                          2.2.0  h2699725_0          conda-forge/osx-64      269kB
  + ca-certificates               2022.6.15  h033912b_0          conda-forge/osx-64     Cached
  + cairo                            1.16.0  h1680b09_1011       conda-forge/osx-64        1MB
  + cfitsio                           4.1.0  h2c97ad1_0          conda-forge/osx-64        1MB
  + charls                            2.3.4  he49afe7_0          conda-forge/osx-64      116kB
  + cloudpickle                       2.1.0  pyhd8ed1ab_0        conda-forge/noarch       25kB
  + cytoolz                          0.12.0  py39h701faf5_0      conda-forge/osx-64      343kB
  + dask-core                      2022.7.0  pyhd8ed1ab_0        conda-forge/noarch      860kB
  + expat                             2.4.8  h96cf925_0          conda-forge/osx-64      150kB
  + ffmpeg                            4.4.2  h8454a6e_0          conda-forge/osx-64       11MB
  + font-ttf-dejavu-sans-mono          2.37  hab24e00_0          conda-forge/noarch      397kB
  + font-ttf-inconsolata              3.000  h77eed37_0          conda-forge/noarch       97kB
  + font-ttf-source-code-pro          2.038  h77eed37_0          conda-forge/noarch      701kB
  + font-ttf-ubuntu                    0.83  hab24e00_0          conda-forge/noarch        2MB
  + fontconfig                       2.14.0  h676cef8_0          conda-forge/osx-64      288kB
  + fonts-conda-ecosystem                 1  0                   conda-forge/noarch        4kB
  + fonts-conda-forge                     1  0                   conda-forge/noarch        4kB
  + freetype                         2.10.4  h4cff582_1          conda-forge/osx-64     Cached
  + fsspec                         2022.5.0  pyhd8ed1ab_0        conda-forge/noarch       98kB
  + gettext                        0.19.8.1  hd1a6beb_1008       conda-forge/osx-64     Cached
  + giflib                            5.2.1  hbcb3906_2          conda-forge/osx-64       73kB
  + gmp                               6.2.1  h2e338ed_0          conda-forge/osx-64      792kB
  + gnutls                            3.7.6  h047ecf1_5          conda-forge/osx-64        2MB
  + graphite2                        1.3.13  h2e338ed_1001       conda-forge/osx-64       87kB
  + harfbuzz                          4.4.1  h00bb2c2_0          conda-forge/osx-64        2MB
  + hdf5                             1.12.1  nompi_h0aa1fa2_104  conda-forge/osx-64        4MB
  + icu                                70.1  h96cf925_0          conda-forge/osx-64       14MB
  + imagecodecs                   2022.2.22  py39h7c839d0_6      conda-forge/osx-64        2MB
  + imageio                          2.19.3  pyhcf75d05_0        conda-forge/noarch        3MB
  + jasper                           2.0.33  h013e400_0          conda-forge/osx-64        1MB
  + joblib                            1.1.0  pyhd8ed1ab_0        conda-forge/noarch     Cached
  + jpeg                                 9e  hac89ed1_2          conda-forge/osx-64      267kB
  + jxrlib                              1.1  h35c211d_2          conda-forge/osx-64      231kB
  + krb5                             1.19.3  hb98e516_0          conda-forge/osx-64        1MB
  + lame                              3.100  h35c211d_1001       conda-forge/osx-64      534kB
  + lcms2                              2.12  h577c468_0          conda-forge/osx-64     Cached
  + lerc                                3.0  he49afe7_0          conda-forge/osx-64     Cached
  + libaec                            1.0.6  he49afe7_0          conda-forge/osx-64       38kB
  + libavif                          0.10.1  h5eb16cf_0          conda-forge/osx-64       92kB
  + libblas                           3.9.0  15_osx64_mkl        conda-forge/osx-64       13kB
  + libbrotlicommon                   1.0.9  h5eb16cf_7          conda-forge/osx-64     Cached
  + libbrotlidec                      1.0.9  h5eb16cf_7          conda-forge/osx-64     Cached
  + libbrotlienc                      1.0.9  h5eb16cf_7          conda-forge/osx-64     Cached
  + libcblas                          3.9.0  15_osx64_mkl        conda-forge/osx-64       13kB
  + libcurl                          7.83.1  h23f1065_0          conda-forge/osx-64      325kB
  + libcxx                           14.0.6  hce7ea42_0          conda-forge/osx-64        1MB
  + libdeflate                         1.12  hac89ed1_0          conda-forge/osx-64       86kB
  + libedit                    3.1.20191231  h0678c8f_2          conda-forge/osx-64     Cached
  + libev                              4.33  haf1e3a3_1          conda-forge/osx-64     Cached
  + libffi                            3.4.2  h0d85af4_5          conda-forge/osx-64     Cached
  + libgfortran                       5.0.0  9_3_0_h6c81a4c_23   conda-forge/osx-64     Cached
  + libgfortran5                      9.3.0  h6c81a4c_23         conda-forge/osx-64     Cached
  + libglib                          2.72.1  hfbcb929_0          conda-forge/osx-64        3MB
  + libiconv                           1.16  haf1e3a3_0          conda-forge/osx-64     Cached
  + libidn2                           2.3.3  hac89ed1_0          conda-forge/osx-64      173kB
  + liblapack                         3.9.0  15_osx64_mkl        conda-forge/osx-64       13kB
  + liblapacke                        3.9.0  15_osx64_mkl        conda-forge/osx-64       13kB
  + libnghttp2                       1.47.0  hca56917_0          conda-forge/osx-64      895kB
  + libopencv                         4.6.0  py39h6ed1040_0      conda-forge/osx-64       33MB
  + libpng                           1.6.37  h5a3d3bf_3          conda-forge/osx-64      319kB
  + libprotobuf                      3.20.1  h2292cb8_0          conda-forge/osx-64        2MB
  + libssh2                          1.10.0  hd3787cc_2          conda-forge/osx-64      227kB
  + libtasn1                         4.18.0  hac89ed1_1          conda-forge/osx-64      110kB
  + libtiff                           4.4.0  h9847915_1          conda-forge/osx-64      620kB
  + libunistring                     0.9.10  h0d85af4_0          conda-forge/osx-64        1MB
  + libvpx                           1.11.0  he49afe7_3          conda-forge/osx-64        1MB
  + libwebp                           1.2.2  h28dabe5_0          conda-forge/osx-64       81kB
  + libwebp-base                      1.2.2  h0d85af4_1          conda-forge/osx-64     Cached
  + libxcb                             1.13  h0d85af4_1004       conda-forge/osx-64      312kB
  + libxml2                          2.9.14  h08a9926_3          conda-forge/osx-64      697kB
  + libzlib                          1.2.12  hfe4f2af_2          conda-forge/osx-64     Cached
  + libzopfli                         1.0.3  h046ec9c_0          conda-forge/osx-64      162kB
  + llvm-openmp                      14.0.4  ha654fa7_0          conda-forge/osx-64      337kB
  + locket                            1.0.0  pyhd8ed1ab_0        conda-forge/noarch        8kB
  + lz4-c                             1.9.3  he49afe7_1          conda-forge/osx-64     Cached
  + mkl                            2022.1.0  h860c996_928        conda-forge/osx-64      198MB
  + mkl-devel                      2022.1.0  h694c41f_929        conda-forge/osx-64       21kB
  + mkl-include                    2022.1.0  h6bab518_928        conda-forge/osx-64      681kB
  + ncurses                             6.3  h96cf925_1          conda-forge/osx-64      937kB
  + nettle                              3.8  h96f3785_0          conda-forge/osx-64      546kB
  + networkx                          2.8.4  pyhd8ed1ab_0        conda-forge/noarch        2MB
  + numpy                            1.23.1  py39hda39a74_0      conda-forge/osx-64        7MB
  + opencv                            4.6.0  py39h6e9494a_0      conda-forge/osx-64       24kB
  + openh264                          2.1.1  hfd3ada9_0          conda-forge/osx-64        2MB
  + openjpeg                          2.4.0  h6e7aa92_1          conda-forge/osx-64     Cached
  + openssl                           3.0.5  hfe4f2af_0          conda-forge/osx-64        3MB
  + p11-kit                          0.24.1  h65f8906_0          conda-forge/osx-64      834kB
  + packaging                          21.3  pyhd8ed1ab_0        conda-forge/noarch     Cached
  + partd                             1.2.0  pyhd8ed1ab_0        conda-forge/noarch       18kB
  + pcre                               8.45  he49afe7_0          conda-forge/osx-64     Cached
  + pillow                            9.2.0  py39h579eac4_0      conda-forge/osx-64       47MB
  + pip                              22.1.2  pyhd8ed1ab_0        conda-forge/noarch        2MB
  + pixman                           0.40.0  hbcb3906_0          conda-forge/osx-64      629kB
  + pthread-stubs                       0.4  hc929b4f_1001       conda-forge/osx-64        6kB
  + py-opencv                         4.6.0  py39h71a6800_0      conda-forge/osx-64        1MB
  + pyparsing                         3.0.9  pyhd8ed1ab_0        conda-forge/noarch       81kB
  + python                           3.9.13  hf8d34f4_0_cpython  conda-forge/osx-64       13MB
  + python_abi                          3.9  2_cp39              conda-forge/osx-64        4kB
  + pytorch                          1.12.0  py3.9_0             pytorch/osx-64           79MB
  + pywavelets                        1.3.0  py39h86b5767_1      conda-forge/osx-64        4MB
  + pyyaml                              6.0  py39h63b48b0_4      conda-forge/osx-64      176kB
  + qudida                            0.0.4  pyhd8ed1ab_0        conda-forge/noarch        7kB
  + readline                          8.1.2  h3899abd_0          conda-forge/osx-64     Cached
  + scikit-image                     0.19.3  py39hf72b562_0      conda-forge/osx-64       12MB
  + scikit-learn                      1.1.1  py39hafe9688_0      conda-forge/osx-64        8MB
  + scipy                             1.8.1  py39hfa1a3ab_0      conda-forge/osx-64       23MB
  + setuptools                       63.2.0  py39h6e9494a_0      conda-forge/osx-64        1MB
  + snappy                            1.1.9  h6e38e02_1          conda-forge/osx-64       32kB
  + sqlite                           3.39.1  hd9f0692_0          conda-forge/osx-64     Cached
  + svt-av1                           1.1.0  hb486fe8_1          conda-forge/osx-64        3MB
  + tbb                            2021.5.0  hbb4e6a2_1          conda-forge/osx-64      161kB
  + threadpoolctl                     3.1.0  pyh8a188c0_0        conda-forge/noarch       18kB
  + tifffile                       2022.5.4  pyhd8ed1ab_0        conda-forge/noarch      153kB
  + tk                               8.6.12  h5dbffcc_0          conda-forge/osx-64     Cached
  + toolz                            0.12.0  pyhd8ed1ab_0        conda-forge/noarch       49kB
  + typing-extensions                 4.3.0  hd8ed1ab_0          conda-forge/noarch        8kB
  + typing_extensions                 4.3.0  pyha770c72_0        conda-forge/noarch       29kB
  + tzdata                            2022a  h191b570_0          conda-forge/noarch      124kB
  + wheel                            0.37.1  pyhd8ed1ab_0        conda-forge/noarch     Cached
  + x264                         1!161.3030  h0d85af4_1          conda-forge/osx-64        3MB
  + x265                                3.5  hbb4e6a2_3          conda-forge/osx-64        3MB
  + xorg-libxau                       1.0.9  h35c211d_0          conda-forge/osx-64       11kB
  + xorg-libxdmcp                     1.1.3  h35c211d_0          conda-forge/osx-64       17kB
  + xz                                5.2.5  haf1e3a3_1          conda-forge/osx-64     Cached
  + yaml                              0.2.5  h0d85af4_2          conda-forge/osx-64     Cached
  + zfp                               0.5.5  h4a89273_8          conda-forge/osx-64      176kB
  + zlib                             1.2.12  hfe4f2af_2          conda-forge/osx-64     Cached
  + zlib-ng                           2.0.6  hac89ed1_0          conda-forge/osx-64      100kB
  + zstd                              1.5.2  ha9df2e0_2          conda-forge/osx-64      477kB

  Summary:

  Install: 139 packages

  Total download: 518MB

────────────────────────────────────────────────────────────────────────────────────────────────

```
</details>

**Comment by croth1** [comment]
Looking a bit deeper into it, I think the root problem seems that the pytorch channel ships its own pytorch::ffmpeg, which is incompatible with conda-forge. When using strict channel-ordering (which is strongly recommended by conda-forge), mamba is forced to solve conda-forge packages with pytorch::ffmpeg, which fails for python>3.8.

Note that with py3.8, it still solves fine: `mamba create -n foo --dry-run --channel pytorch --channel conda-forge 'python=3.8' 'pytorch=1.12' 'albumentations=1.2.1'`

There also does not seem to be an easy way to overwrite the channel order (this does not seem to work):

Note that with py3.8, it still solves fine: `mamba create -n foo --dry-run --channel pytorch --channel conda-forge 'python=3.8' 'pytorch=1.12' 'albumentations=1.2.1'  conda-forge::ffmpeg`

```
Looking for: ['python=3.9', 'pytorch=1.12', 'albumentations=1.2.1', 'conda-forge::ffmpeg']

conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache
conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache
pytorch/osx-64                                                No change
pytorch/noarch                                                No change
Encountered problems while solving:
  - package ffmpeg-5.0.1-lgpl_ha649829_7 is excluded by strict repo priority
```

What is strange to me is that:
1. despite having `channel_priority: strict` in my `.condarc`, `mamba env create` successfully solves by pulling conda-forge::ffmpeg (cc @wolfv)
2. by shipping its own ffmpeg instead of using conda-forge::ffmpeg, the pytorch and conda-forge channels seem to become incompatible - at least with `channel_order: strict` which is strongly recommended by conda-forge. (cc @seemethere)

**Comment by mariusvniekerk** [comment]
You can probably make use of a temporary `$CONDARC` that allows flexible channel priority.  

For the most part, if you don't have the defaults channel at all strict channel priority isn't as necessary.  Particularly if you make a locked env using conda lock and test your application in it.
