### ISSUE TITLE
conda-lock install: distracting error message when git is not available

### ISSUE THREAD

**Issue by aaron-kaplan** [conda-incubator/conda-lock#254]
When I run `conda-lock install` in a container that doesn't have git installed, it prints the following error message::

```
[Errno 2] No such file or directory: 'git'
Traceback (most recent call last):
  File "/conda/lib/python3.9/site-packages/conda_lock/vendor/conda/auxlib/packaging.py", line 165, in get_version
    return _get_version_from_version_file(path) or _get_version_from_git_clone(path)
  File "/conda/lib/python3.9/site-packages/conda_lock/vendor/conda/auxlib/packaging.py", line 146, in _get_version_from_git_clone
    tag = _git_describe_tags(path) or ''
  File "/conda/lib/python3.9/site-packages/conda_lock/vendor/conda/auxlib/packaging.py", line 114, in _git_describe_tags
    call("git update-index --refresh", path, raise_on_error=False)
  File "/conda/lib/python3.9/site-packages/conda_lock/vendor/conda/auxlib/packaging.py", line 92, in call
    p = Popen(shlex_split_unicode(command), cwd=path, stdout=PIPE, stderr=PIPE)
  File "/conda/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/conda/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

It seems the error is not fatal, as installation eventually succeeds, but it led me down the wrong path when I was trying to debug an environment that was failing for what turned out to be unrelated reasons.

**Comment by mariusvniekerk** [comment]
this is fixed on master
