### ISSUE TITLE
Resolving pip dependencies with uppercase characters fails

### ISSUE THREAD

**Issue by HedgehogCode** [conda-incubator/conda-lock#264]
If I have pip dependencies that have uppercase characters in the name `conda-lock` will fail with a `KeyError`. Note, that pip is case insensitive. Therefore it is easy to fix the environment definition by not using upper-case letters. However, `conda-lock` should also be case insensitive when handling pip dependencies. 

Try the following environment definition (`env.yml`):
```yaml
name: myenv
channels:
- conda-forge
dependencies:
- pip
- pip:
  - MIDIFile
```

Error:
```
$ conda-lock lock -f env.yml
Locking dependencies for ['linux-64', 'osx-64', 'win-64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['pip *']
Traceback (most recent call last):
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/src_parser/__init__.py", line 283, in seperator_munge_get
    return d[key]
KeyError: 'MIDIFile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/src_parser/__init__.py", line 286, in seperator_munge_get
    return d[key.replace("-", "_")]
KeyError: 'MIDIFile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/bin/conda-lock", line 10, in <module>
    sys.exit(main())
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 1190, in lock
    lock_func(
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 949, in run_lock
    make_lock_files(
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 389, in make_lock_files
    lock_content = lock_content | create_lockfile_from_spec(
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 737, in create_lockfile_from_spec
    deps = _solve_for_arch(
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 703, in _solve_for_arch
    pip_deps = solve_pypi(
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/pypi_solver.py", line 319, in solve_pypi
    src_parser._apply_categories(requested=pip_specs, planned=planned)
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/src_parser/__init__.py", line 297, in _apply_categories
    for dep in seperator_munge_get(planned, item).dependencies
  File "/home/benjamin/miniconda3/envs/conda-lock-dev/lib/python3.10/site-packages/conda_lock/src_parser/__init__.py", line 288, in seperator_munge_get
    return d[key.replace("_", "-")]
KeyError: 'MIDIFile'
```

conda-lock version:
```
$ conda list | grep conda-lock         
conda-lock                1.2.1              pyhd8ed1ab_0    conda-forge
```

**Comment by mariusvniekerk** [comment]
Addressed in #268
