### ISSUE TITLE
RuntimeError: Cannot find platform in lockfile.

### ISSUE THREAD

**Issue by hanm2019** [conda-incubator/conda-lock#269]
I try to install Chipyard in ubuntu18.04. 
the command is `conda-lock install -p /home/ubuntu/chipyard/.conda-env /home/ubuntu/chipyard/conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml`

and get: 
```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda-lock", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 1100, in install
    do_validate_platform(lockfile)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 127, in do_validate_platform
    platform_lockfile = extract_platform(lockfile)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 108, in extract_platform
    raise RuntimeError("Cannot find platform in lockfile.")
RuntimeError: Cannot find platform in lockfile.
```

the lock file can be found at : https://github.com/ucb-bar/chipyard/blob/main/conda-reqs/conda-lock-reqs/conda-requirements-esp-tools-linux-64.conda-lock.yml

**Comment by maresb** [comment]
I suspect that this is due to running an outdated version of `conda-lock`. Could you please upgrade to the latest version and try again?

**Comment by hanm2019** [comment]
how can I get the version of the conda-lock? and upgrade it?

I install the conda-lock by `conda install -c conda-forge conda-lock`

**Comment by maresb** [comment]
Thanks for reporting back! You can try `conda upgrade -c conda-forge conda-lock`. Alternatively, `conda install -c conda-forge "conda-lock>0.13.2"`.

Also, I'd recommend using `mamba` as a drop-in replacement for `conda`, as it's much, much faster.

**Comment by hanm2019** [comment]
It works! It seem that the version of conda-lock in anaconda is 0.13.2.
