### ISSUE TITLE
lock fails with pytorch (and other gpu enabled codes) from pyproject.toml source.

### ISSUE THREAD

**Issue by PanayotisManganaris** [conda-incubator/conda-lock#279]
similar but slightly different to issues #253 and #179.

Using conda-lock v1.2.1 with python 3.10.4. I'm also running into a keyerror when attempting to create a cond-lock file. However, I'm using a poetry pyproject.toml as source.

my pyproject.toml:
```toml
[tool.poetry]
name = "test"
version = "0.0.0"
description = "test"
authors = ["me"]
readme = "README.org"

[tool.poetry.dependencies]
python = "^3.7"
pytorch = "^1.7.1"
```

this results in:
```
Locking dependencies for ['linux-64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['python >=3.7,<4.0', 'pytorch >=1.7.1,<2.0.0']
Traceback (most recent call last):
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/src_parser/__init__.py", line 283, in seperator_munge_get
    return d[key]
KeyError: 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/src_parser/__init__.py", line 286, in seperator_munge_get
    return d[key.replace("-", "_")]
KeyError: 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/depot/amannodi/apps/bigconda/envs/alignn/bin/conda-lock", line 10, in <module>
    sys.exit(main())
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 1190, in lock
    lock_func(
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 949, in run_lock
    make_lock_files(
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 389, in make_lock_files
    lock_content = lock_content | create_lockfile_from_spec(
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 737, in create_lockfile_from_spec
    deps = _solve_for_arch(
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 689, in _solve_for_arch
    conda_deps = solve_conda(
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/conda_solver.py", line 211, in solve_conda
    _apply_categories(
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/src_parser/__init__.py", line 297, in _apply_categories
    for dep in seperator_munge_get(planned, item).dependencies
  File "/depot/amannodi/apps/bigconda/envs/alignn/lib/python3.10/site-packages/conda_lock/src_parser/__init__.py", line 288, in seperator_munge_get
    return d[key.replace("_", "-")]
KeyError: 'pip'
```

This example with a single pytorch specification can probably be worked around by just making an env.yaml, but for convenience it would be nice if this issue were addressed. conda-lock is a wonderful companion to poetry projects and data scientists especially.

**Comment by PanayotisManganaris** [comment]
This seems not to to actually be a problem with conda-lock. More likely something about the environment I installed into was obstructing the lock. It was a conda environment in a remote cluster.
