### ISSUE TITLE
Getting `Unable to parse "*"` when creating lock file

### ISSUE THREAD

**Issue by the-matt-morris** [conda-incubator/conda-lock#302]
Hello, thank you for this great library!

I had been using it without any trouble until recently when I encountered an issue trying to create the `conda-lock.yml` file, and I have narrowed it down to it having troubles with any dependencies that have `source = "pypi"`.  The strange thing is that this used to work, and the source libraries have not changed.  I have even tried with older versions of `conda-lock` and still seeing this issue, which is really puzzling, so I may be doing something wrong.

Here is a `pyproject.toml` that has only one dependency that causes this error.

```toml
[build-system]
requires = [ "poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "my-project"
description = "none"
authors = [ "Me <first.last@gmail.com>"]
version = "0"

[tool.conda-lock]
channels = [ "conda-forge", "defaults", "pip"]

[tool.poetry.dependencies]
python = "~3.9"
libgeohash = { version = "^0.1.1", source = "pypi"}
```

```
conda-lock -f pyproject.toml
```

```
Locking dependencies for ['linux-64', 'osx-64', 'win-64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['python >=3.9,<3.10']
Traceback (most recent call last):
  File "/usr/local/bin/conda-lock", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 1341, in lock
    lock_func(
  File "/usr/local/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 1071, in run_lock
    make_lock_files(
  File "/usr/local/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 407, in make_lock_files
    lock_content = lock_content | create_lockfile_from_spec(
  File "/usr/local/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 800, in create_lockfile_from_spec
    deps = _solve_for_arch(
  File "/usr/local/lib/python3.9/site-packages/conda_lock/conda_lock.py", line 736, in _solve_for_arch
    pip_deps = solve_pypi(
  File "/usr/local/lib/python3.9/site-packages/conda_lock/pypi_solver.py", line 246, in solve_pypi
    locked.add_package(get_package(spec))
  File "/usr/local/lib/python3.9/site-packages/conda_lock/pypi_solver.py", line 171, in get_package
    return Package(locked.name, version=locked.version)
  File "/usr/local/lib/python3.9/site-packages/conda_lock/_vendor/poetry/core/packages/package.py", line 77, in __init__
    self._version = Version.parse(version)
  File "/usr/local/lib/python3.9/site-packages/conda_lock/_vendor/poetry/core/semver/version.py", line 211, in parse
    raise ParseVersionError('Unable to parse "{}".'.format(text))
conda_lock._vendor.poetry.core.semver.exceptions.ParseVersionError: Unable to parse "*".
```

I saw the same error when using dependency `libgeohash = { version = "^0.1.1", source = "pypi"}`.

I thought perhaps it was something with these dependencies, but `poetry` can create `poetry.lock` with no issues.

Environment:

```
Debian GNU/Linux 11 (bullseye)
conda-lock 1.3.0
```

**Comment by the-matt-morris** [comment]
Well I think I may have figured out what I screwed up, though it's clear I'm ignorant on the internals of `conda-lock`.  When I delete my existing `conda-lock.yml` file, I can rebuild it with this `pyproject.toml`.  My existing `conda-lock.yml` file was corrupt because I hacked some entries for private GitHub repos, and it didn't like me putting "*" as the version (though it does build).  Closing this.
