### ISSUE TITLE
[Bug] Fix error handling for mamba install

### ISSUE THREAD

**Issue by janjagusch** [conda-incubator/conda-lock#80]
I noticed that the error handling breaks sometimes when using `--mamba`.
For example, here I am using a `lock` file that has its basic auth stripped. So I expect a `401 Unauthorized` error to occur.

The error is raised correctly without the `--mamba argument`

```sh
Failed to parse json, Extra data: line 2 column 1 (char 76)
Could not perform conda install using /var/folders/mj/2sx68gpn1bldjjpwtbqs8gfr0000gn/T/tmpt60id44_ lock file into None
    Command: ['/usr/local/Caskroom/miniforge/base/bin/conda', 'create', '--file', '/var/folders/mj/2sx68gpn1bldjjpwtbqs8gfr0000gn/T/tmpt60id44_', '--yes', '--json', '--name', 'test']
    STDOUT:
{"fetch":"qc_drg_grouper_binar | ","finished":true,"maxval":1,"progress":1}
{
  "error": "Multiple Errors Encountered.",
  "errors": [
    {
      "caused_by": "HTTPError('401 Client Error: Unauthorized for url: <url to package>')",
      "elapsed_time": "00:00.127258",
      "error": "CondaHTTPError: HTTP 401 UNAUTHORIZED for url <<url to package>>\nElapsed: 00:00.127258\n\nAn HTTP error occurred when trying to retrieve this URL.\nHTTP errors are often intermittent, and a simple retry will get you on your way.\n",
      "exception_name": "CondaHTTPError",
      "exception_type": "<class 'conda.exceptions.CondaHTTPError'>",
      "message": "HTTP 401 UNAUTHORIZED for url <<url to package>>\nElapsed: 00:00.127258\n\nAn HTTP error occurred when trying to retrieve this URL.\nHTTP errors are often intermittent, and a simple retry will get you on your way.\n",
      "reason": "UNAUTHORIZED",
      "response_details": "",
      "status_code": 401,
      "url": "<url to package>"
    }
  ],
  "exception_name": "CondaMultiError",
  "exception_type": "<class 'conda.CondaMultiError'>"
}
```

But once I add the `--mamba` argument, the error handling fails with `KeyError: 'message'`

```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda_lock/conda_lock.py", line 163, in do_conda_install
    proc.check_returncode()
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/local/Caskroom/miniforge/base/bin/mamba', 'create', '--file', '/var/folders/mj/2sx68gpn1bldjjpwtbqs8gfr0000gn/T/tmpat1dqpf7', '--yes', '--json', '--name', 'test']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/conda-lock-no-auth", line 228, in <module>
    main()
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./bin/conda-lock-no-auth", line 224, in install
    do_conda_install(conda=_conda_exe, prefix=prefix, name=name, file=lock_file, auth=auth)
  File "./bin/conda-lock-no-auth", line 112, in do_conda_install
    _do_conda_install(conda=conda, prefix=prefix, name=name, file=file)
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda_lock/conda_lock.py", line 168, in do_conda_install
    message = err_json["message"]
KeyError: 'message'
```

This is the format of the mamba `err_json`:
```
{
    "error": "Multiple Errors Encountered.",
    "errors": [
        {
            "caused_by": "HTTPError("401 Client Error: Unauthorized for url: <url to package>")",
            "elapsed_time": "00: 00.182042",
            "error": "CondaHTTPError: HTTP 401 UNAUTHORIZED for url <<url to package>>\nElapsed: 00: 00.182042\n\nAn HTTP error occurred when trying to retrieve this URL.\nHTTP errors are often intermittent, and a simple retry will get you on your way.\n",
            "exception_name": "CondaHTTPError",
            "exception_type": "<class "conda.exceptions.CondaHTTPError">",
            "message": "HTTP 401 UNAUTHORIZED for url <<url to package>>\nElapsed: 00: 00.182042\n\nAn HTTP error occurred when trying to retrieve this URL.\nHTTP errors are often intermittent, and a simple retry will get you on your way.\n",
            "reason": "UNAUTHORIZED",
            "response_details": "",
            "status_code": 401,
            "url": "<url to package>"
        }
    ],
    "exception_name": "CondaMultiError",
    "exception_type": "<class "conda.CondaMultiError">"
}
```

My suggestion is to also handle the `KeyError` and print `err_json` in that case.

*Note: I replaced the actual url with `<url to package>` in all examples.*

**Comment by mariusvniekerk** [comment]
Sounds like the right plan

**Comment by janjagusch** [comment]
Cool, I'll open a PR then. :)

**Comment by janjagusch** [comment]
Update: I was wrong with my first assumption.

* without `--mamba`: parsing the `proc.stdout` results in an `JSONDecodeError` before a possible `KeyError` can be thrown (which would totally be the case)
* with `--mamba`: the `proc.stdout` contains valid JSON and raises a `KeyError` because there is no `message` property on the root level.

So the actual solution would be:

1. Make sure that the `proc.stdout` for runs without `--mamba` can be parsed to JSON correctly
2. Make sure to extract the right property from the JSON objects

That's what I did in the linked PR. :)
