### ISSUE TITLE
Fail early when platform is incompatible

### ISSUE THREAD

**Issue by janjagusch** [conda-incubator/conda-lock#93]
I encountered a strange problem today when trying to install a lockfile. After a while I realised I tried to install a `linux-64` lockfile on an `osx-64` system.

Considering that we have the `platform` information in the lockfile itself, we could test at the very beginning whether they are compatible and, if not, fail with a more meaningful error. What do you think?

---

For completeness, here's the error I got:

```
ERROR:root:# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
ERROR:root:
ERROR:root:    Traceback (most recent call last):
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
ERROR:root:        return func(*args, **kwargs)
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
ERROR:root:        exit_code = do_call(args, p)
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
ERROR:root:        return getattr(module, func_name)(args, parser)
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/cli/main_create.py", line 41, in execute
ERROR:root:        install(args, parser, 'create')
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/cli/install.py", line 195, in install
ERROR:root:        explicit(specs, prefix, verbose=not context.quiet, index_args=index_args)
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/misc.py", line 110, in explicit
ERROR:root:        txn.execute()
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/core/link.py", line 244, in execute
ERROR:root:        self.verify()
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
ERROR:root:        return f(*args, **kwds)
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/core/link.py", line 231, in verify
ERROR:root:        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/core/link.py", line 590, in _verify
ERROR:root:        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/common/io.py", line 525, in map
ERROR:root:        yield func(thing)
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/core/link.py", line 411, in _verify_individual_level
ERROR:root:        error_result = axn.verify()
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/conda/core/path_actions.py", line 323, in verify
ERROR:root:        source_size_in_bytes = getsize(self.source_full_path)
ERROR:root:      File "/usr/local/Caskroom/miniforge/base/lib/python3.8/genericpath.py", line 50, in getsize
ERROR:root:        return os.stat(filename).st_size
ERROR:root:    OSError: [Errno 62] Too many levels of symbolic links: '/usr/local/Caskroom/miniforge/base/pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/NCR260VT300WPP'
```

**Comment by JanJaguschQC** [comment]
Something like a `--validate-platform` CLI argument that defaults to `True`?
Could put something together next week. :)
